# Generated by Django 2.1.7 on 2019-04-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financialmarket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='website',
            field=models.URLField(max_length=500),
        ),
    ]
