# Generated by Django 2.1.7 on 2019-04-07 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Financialmarket', '0002_auto_20190406_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='Financialmarket.CompanyInfo'),
        ),
    ]
