# Generated by Django 2.1.7 on 2019-04-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financialmarket', '0004_auto_20190407_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldprice',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
