# Generated by Django 2.1.7 on 2019-04-08 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financialmarket', '0005_auto_20190407_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldprice',
            name='date',
            field=models.DateField(),
        ),
    ]
